# Generated by Django 4.2 on 2023-05-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_post_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='fails',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feed',
            name='followed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feed',
            name='stopped',
            field=models.BooleanField(default=False),
        ),
    ]
