# Generated by Django 4.2 on 2023-05-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_feed_fails_alter_feed_followed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='followed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='readed',
            field=models.BooleanField(default=False),
        ),
    ]
