# Generated by Django 5.0.6 on 2024-06-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
